### ISSUE TITLE
[question] how can I eval two different data on the same schema?

### ISSUE THREAD

**Issue by quantang** [saintkepha/yang-js#79]
Hi @saintkepha ,

Do you have any idea how I can eval different data without merging them?

As my scenario may get different JSON data from different sources, I use yang-js to eval the data against my schema first, then I retrieve the cooked data from YANG model for further processing.

Currently, my code can work well if I only deal with one JSON data. If there is another JSON data and I use YANG instance to eval it, it will be merged into the existing YANG model, right?

Please correct me if I use it incorrectly.

Cheers,
Quan

**Comment by quantang** [comment]
Hi @saintkepha ,

Here is my sample code and the output:

Code:
```
const Yang = require('yang-js');

const data1 = {
    "ietf-network:networks": {
        "network": [{
            "network-id": "local.area.atmf",
        }]
    }
};

const data2 = {
    "ietf-network:networks": {
        "network": [{
            "network-id": "wireless.awc",
        }]
    }
};


const Topo = Yang.import('at-network-topology');

const model1 = Topo.eval(data1);
const networks1 = model1.access('ietf-network');
console.info('network from data1:');
console.info(JSON.stringify(networks1));

const model2 = Topo.eval(data2);
const networks2 = model2.access('ietf-network');
console.info('network from data2:');
console.info(JSON.stringify(networks2));
```

The output only has the data of the first one:
```
network from data1:
{"ietf-network:networks":{"network":[{"network-id":"local.area.atmf"}]}}
network from data2:
{"ietf-network:networks":{"network":[{"network-id":"local.area.atmf"}]}}
```

Please correct me if I am wrong.
Cheers.

**Comment by saintkepha** [comment]
Yes, that is the issue I was indicating in my prior note.

> The only caveat is how it
> deals with data for imported module schemas. It currently pulls from
> Model.Store which is a singleton instance.

The way yang-js currently handles data for imported modules is that it uses a singleton object and it results in bleedover in this scenario. Let me change the Model class instance to hold the models for imported modules instead of the Model class itself and it should allow this use case to operate as expected.

**Comment by quantang** [comment]
Ok, I see your point.
It is not a high priority issue for us, as I can work it around and eventually merge them into a single one.
Cheers.
